# Generated by Django 4.1.1 on 2023-07-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=100)),
                ('Sname', models.CharField(max_length=100)),
                ('RegNO', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
