# Generated by Django 4.1.1 on 2023-07-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_students_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='RegNO',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.TextField(),
        ),
    ]
