# Generated by Django 4.1.1 on 2023-07-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_regno_student_date_alter_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='memory',
        ),
        migrations.AddField(
            model_name='student',
            name='head',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
