# Generated by Django 4.1.1 on 2023-07-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='id',
        ),
        migrations.AddField(
            model_name='creator',
            name='creatorID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
