# Generated by Django 4.1.1 on 2023-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_creator_id_creator_creatorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='creatorID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
